import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Navigation from '../components/Navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Learn Bee',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header
          isLogged={false}
        />
        <main>
          <div className='grid grid-cols-5'>
            <Navigation/>
            <div className='px-5 col-span-3'>{children}</div>
          </div>
        </main>
      </body>
    </html>
  )
}
